- name: Using vaults
  hosts: nodes
  gather_facts: no
  tasks:
    - name: Display secret password from the first vault
      debug:
        var: bd_pass

    - name: Read content of the encrypted file
      copy:
        src: confidential_data.txt
        dest: /tmp/confidential_data.txt

    - name: Display content of the encrypted file
      cat:
        path: /tmp/confidential_data.txt

