---
- name: Install and Configure Nginx
  hosts: webserver
  become: yes
  gather_facts: no
  vars:
    nginx_root_dir: /opt/nginx/html
  tasks:
    - name: Gather facts from tiberna-rasp-001
      setup:
      delegate_to: tiberna-rasp-001
    
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Deploy nginx.conf
      template:
        src: templates/lb.conf.j2
        dest: "{{ nginx_root_dir }}/lb.conf"
        owner: root
        group: root
        mode: '0777'
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
