- name: Error handling using handlers
  hosts: nodes
  gather_facts: no
  vars:
    filename: "users.csv"
  tasks:
    - name: Read users from CSV
      set_fact:
        user_data: "{{ lookup('csvfile', 'user file=./' + filename delimiter=,') }}"
      run_once: true  # This ensures the CSV is read only once, not for every host

    - name: Print "users.csv" contents
      debug:
        msg: "Username: {{ item.0 }}, Group: {{ item.1 }}, Password: {{ item.2 | password_hash('sha512') }}"
      loop: "{{ user_data }}"

    # - name: Create users
    #   user:
    #     name: "{{ item.0 }}"
    #     group: "{{ item.1 }}"
    #     password: "{{ item.2 | password_hash('sha512') }}"  # Hashing the password
    #     state: present
    #   loop: "{{ user_data }}"

